version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  target-branch: master
  labels:
  - dependency_updates
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  target-branch: master
  labels:
  - CI
