repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
    exclude: README.md
  - id: check-yaml
  - id: check-json

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    name: Blacken

- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
  - id: flake8
