repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
    exclude: README.md
  - id: check-yaml
  - id: check-json

- repo: https://github.com/ambv/black
  rev: 24.4.2
  hooks:
  - id: black
    name: Blacken

- repo: https://github.com/pycqa/flake8
  rev: '7.0.0'
  hooks:
  - id: flake8
